language: rust
cache: cargo
rust:
  - nightly
os:
  - linux
  - osx

env:
  # Ensure that we build without warnings.
  - CARGO_FLAGS="--features 'strict'"

before_script:
  # Install rustfmt 0.9.0 if it isn't already installed on
  # Travis. This can be slow to install, so raise the Travis timeout.
  - (which rustfmt && rustfmt --version && [ "$(rustfmt --version)" = 0.9.0-* ]) || travis_wait cargo install --force rustfmt --vers 0.9.0

script:
  - cargo test --manifest-path=tests/Cargo.toml

notifications:
  fast_finish: true
  email: false