[package]
name = "mock_derive"
version = "0.3.0"
authors = ["DavidDeSimone <lord.good.mail@gmail.com>"]

[dependencies]
quote = "0.3"
syn = { version = "0.11.11", features = ["full"] }

[lib]
proc-macro = true